
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AM_PM AT BOOK CANCEL COLON COMMA CONFIRM DATE FOR FROM HELP LIST NAME NUMBER ON PAY ROUTE SCHEDULE TICKETS TIME TOcommand : BOOK NUMBER TICKETS TO NAME ON DATE AT TIME FOR NAMEcommand : LIST NAME ROUTE FROM NAME TO NAMEcommand : LIST NAME SCHEDULEcommand : HELP'
    
_lr_action_items = {'BOOK':([0,],[2,]),'LIST':([0,],[3,]),'HELP':([0,],[4,]),'$end':([1,4,9,17,21,],[0,-4,-3,-2,-1,]),'NUMBER':([2,],[5,]),'NAME':([3,10,11,15,20,],[6,12,13,17,21,]),'TICKETS':([5,],[7,]),'ROUTE':([6,],[8,]),'SCHEDULE':([6,],[9,]),'TO':([7,13,],[10,15,]),'FROM':([8,],[11,]),'ON':([12,],[14,]),'DATE':([14,],[16,]),'AT':([16,],[18,]),'TIME':([18,],[19,]),'FOR':([19,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> BOOK NUMBER TICKETS TO NAME ON DATE AT TIME FOR NAME','command',11,'p_command_book','parser.py',8),
  ('command -> LIST NAME ROUTE FROM NAME TO NAME','command',7,'p_command_route','parser.py',27),
  ('command -> LIST NAME SCHEDULE','command',3,'p_command_list','parser.py',36),
  ('command -> HELP','command',1,'p_command_help','parser.py',43),
]
