
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOK CANCEL CONFIRM DATE FOR HELP LIST NAME NUMBER ON PAY SCHEDULE TICKETS TOcommand : BOOK NUMBER TICKETS TO NAME ON DATEcommand : CONFIRM NAME FOR NAMEcommand : PAY NAME FOR NAMEcommand : CANCEL NAME FOR NAMEcommand : LIST NAME SCHEDULEcommand : HELP'
    
_lr_action_items = {'BOOK':([0,],[2,]),'CONFIRM':([0,],[3,]),'PAY':([0,],[4,]),'CANCEL':([0,],[5,]),'LIST':([0,],[6,]),'HELP':([0,],[7,]),'$end':([1,7,17,19,20,21,24,],[0,-6,-5,-2,-3,-4,-1,]),'NUMBER':([2,],[8,]),'NAME':([3,4,5,6,14,15,16,18,],[9,10,11,12,19,20,21,22,]),'TICKETS':([8,],[13,]),'FOR':([9,10,11,],[14,15,16,]),'SCHEDULE':([12,],[17,]),'TO':([13,],[18,]),'ON':([22,],[23,]),'DATE':([23,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> BOOK NUMBER TICKETS TO NAME ON DATE','command',7,'p_command_book','parser.py',16),
  ('command -> CONFIRM NAME FOR NAME','command',4,'p_command_confirm','parser.py',22),
  ('command -> PAY NAME FOR NAME','command',4,'p_command_pay','parser.py',33),
  ('command -> CANCEL NAME FOR NAME','command',4,'p_command_cancel','parser.py',43),
  ('command -> LIST NAME SCHEDULE','command',3,'p_command_list','parser.py',53),
  ('command -> HELP','command',1,'p_command_help','parser.py',60),
]
